---
galaxy_info:
  role_name: rfe_install
  author: jbyrd
  description: Install RFE Bug Tracker Automation Tools
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: macOS
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - 9

dependencies:
  # Let Geerling handle cross-platform concerns
  - role: geerlingguy.git
  - role: geerlingguy.pip
  - role: geerlingguy.homebrew
    when: ansible_os_family == "Darwin"
