---
galaxy_info:
  role_name: miraclemax_services
  author: jbyrd
  description: Deploy Podman services on miraclemax
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - 9

dependencies:
  # Let Geerling handle the infrastructure
  - role: geerlingguy.docker
  - role: geerlingguy.security
  - role: geerlingguy.firewall
